plugins {
    id 'net.neoforged.moddev'
    id 'maven-publish'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"

neoForge {
    version = project.neoforge_version

    parchment {
        minecraftVersion = project.'neoForge.parchment.minecraftVersion'
        mappingsVersion  = project.'neoForge.parchment.mappingsVersion'
    }

    mods {
        routerupgradecore {
            sourceSet sourceSets.main
        }
    }

    runs {
        configureEach {
            logLevel = org.slf4j.event.Level.DEBUG
        }

        client {
            client()
            gameDirectory = project.file('run')
        }

        server {
            server()
            gameDirectory = project.file('run/server')
            programArguments.add('--nogui')
        }

        data {
            data()
            gameDirectory = project.file('run')
            programArguments.addAll(
                    '--mod', mod_id,
                    '--all',
                    '--output', file('src/generated/resources/').absolutePath,
                    '--existing', file('src/main/resources/').absolutePath
            )
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    implementation "maven.modrinth:modular-routers:${modularrouters_version}"

    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('processResources', ProcessResources).configure {
    filteringCharset = 'UTF-8'

    var replaceProperties = [
            minecraft_version: minecraft_version, minecraft_version_range: minecraft_version_range,
            neoforge_version: neoforge_version, neoforge_version_range: neoforge_version_range,
            loader_version_range: loader_version_range,
            mod_id: mod_id, mod_name: mod_name, mod_license: mod_license,
            mod_version: mod_version, mod_authors: mod_authors, mod_description: mod_description,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties + [project: project]
    }
}

tasks.register('apiJar', Jar) {
    archiveClassifier = 'api'
    from sourceSets.main.output
    include 'com/yuuhamu/routerupgradecore/api/**'
}

tasks.register('apiSourcesJar', Jar) {
    archiveClassifier = 'api-sources'
    from sourceSets.main.allJava
    include 'com/yuuhamu/routerupgradecore/api/**'
}

publishing {
    publications {
        api(MavenPublication) {
            groupId = 'com.yuuhamu'
            artifactId = 'routerupgradecore-api'
            version = mod_version
            artifact tasks.apiJar
            artifact tasks.apiSourcesJar
        }
    }
    repositories {
        maven {
            url = uri('.localRepo')
        }
    }
}
