pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
    plugins {
        id 'net.neoforged.moddev' version '2.0.74'
        id 'net.neoforged.moddev.repositories' version '2.0.74'
    }
}
plugins {
    id 'net.neoforged.moddev.repositories'
}
dependencyResolutionManagement {
    repositories {
        maven {
            name = 'NeoForged'
            url = 'https://maven.neoforged.net/releases'
        }
        mavenCentral()
        maven {
            url = 'https://api.modrinth.com/maven'
            content {
                includeGroup 'maven.modrinth'
            }
        }
    }
}

rootProject.name = 'routerupgradecore'
